title: Jia-Xiang Cheng
logo: /assets/img/IMG_1690.png
description: Ph.D. Candidate in Machine Learning for Prognostics and Health Management
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

social:
  linkedin_url: https://www.linkedin.com/in/jiaxiang-cheng/
  scholar_url: https://scholar.google.com/citations?user=fbkjys0AAAAJ&hl=en&inst=8669986779262753491&oi=ao
  github_url: https://github.com/jiaxiang-cheng
